#!/bin/sh 

vol="$(pamixer --get-volume)"

if [ "$vol" -gt "70" ]; then
	icon=""
elif [ "$vol" -gt "30" ]; then
	icon=""
elif [ "$vol" -gt "0" ]; then
	icon=""
else
        echo  && exit
fi

echo "$icon $vol"

case $BLOCK_BUTTON in
    1) pamixer -t;;
    2) $TERMINAL -e pulsemixer;;
    3) pavucontrol;;
    4) pamixer -i 3;;
    5) pamixer -d 3;;
esac
