#!/bin/sh

books="$HOME/Data/Media/Books/"

read="$(fd --base-directory $books --full-path "$books" | dmenu -p "Select the Book: ")"

if [ -z "$read" ]; then
	exit 0
else
	setsid -f zathura $books/"$read"
fi
