#!/bin/sh

opt="$(printf "Yes\\nNo" | dmenu -p "Are you sure to unmount mnt?")"

if [ "$opt" = "Yes" ]; then
	sudo umount $HOME/mnt && notify-send "Unmount Successful"
else
	notify-send "Unmount Aborted"
fi
